# Generated by Django 6.0.3 on 2026-03-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.DeleteModel(
            name='HistoricalProjectImage',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
