# Generated by Django 6.0.3 on 2026-03-21 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_logos', to='media.image'),
        ),
        migrations.AddField(
            model_name='company',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='partnered_with', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyemail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyphone',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyquality',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_icons', to='media.image'),
        ),
        migrations.AddField(
            model_name='company',
            name='qualities',
            field=models.ManyToManyField(blank=True, related_name='companies', to='companies.companyquality'),
        ),
        migrations.AddField(
            model_name='domainactivity',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_icons', to='media.image'),
        ),
        migrations.AddField(
            model_name='company',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='companies', to='companies.domainactivity'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='logo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='media.image'),
        ),
        migrations.AddField(
            model_name='historicalcompanyaddress',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company'),
        ),
        migrations.AddField(
            model_name='historicalcompanyaddress',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompanyemail',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company'),
        ),
        migrations.AddField(
            model_name='historicalcompanyemail',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompanyphone',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company'),
        ),
        migrations.AddField(
            model_name='historicalcompanyphone',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompanyquality',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompanyquality',
            name='icon',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='media.image'),
        ),
        migrations.AddField(
            model_name='historicaldomainactivity',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldomainactivity',
            name='icon',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='media.image'),
        ),
    ]
