# Generated by Django 6.0.3 on 2026-03-21 15:43

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description_ar',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description_fr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='description_ar',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='description_fr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
