# Generated by Django 6.0.3 on 2026-03-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
