# Generated by Django 6.0.3 on 2026-03-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_is_main_historicalcompany_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainactivity',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainactivity',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainactivity',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldomainactivity',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldomainactivity',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldomainactivity',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
